name: Svelte Check

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    svelte-check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: "24"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run Svelte Check
              uses: ofkm/gha-svelte-check@v1.1.5
              with:
                  working-directory: .
                  fail-on-warnings: false
                  fail-on-hints: false
